name: Metrics

on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["main"]}

jobs:
  anilist:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: anilist-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: urabexon
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites,characters
          plugin_anilist_limit: 3
          plugin_anilist_limit_characters: 20
          plugin_anilist_shuffle: yes

  anilist-manga:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: anilist-manga-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: urabexon
          plugin_anilist_medias: manga
          plugin_anilist_sections: reading
          plugin_anilist_limit: 3
          plugin_anilist_limit_characters: 20
          plugin_anilist_shuffle: yes
