name: Metrics

on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: urabexon
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites,characters
          plugin_anilist_limit: 3 
          plugin_anilist_limit_characters: 20
          plugin_anilist_shuffle: yes

          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_limit: 3
          plugin_music_time_range: short
          plugin_music_token: ${{ secrets.SPOTIFY_TOKEN }}
